// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type BulkDeleteRecordsRequest struct {
	// x-collaboration
	XCollaboration *string `header:"style=simple,explode=false,name=x-collaboration"`
	// Tenant Id
	DataPartitionID string   `header:"style=simple,explode=false,name=data-partition-id"`
	RequestBody     []string `request:"mediaType=application/json"`
}

func (o *BulkDeleteRecordsRequest) GetXCollaboration() *string {
	if o == nil {
		return nil
	}
	return o.XCollaboration
}

func (o *BulkDeleteRecordsRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

func (o *BulkDeleteRecordsRequest) GetRequestBody() []string {
	if o == nil {
		return []string{}
	}
	return o.RequestBody
}

type BulkDeleteRecordsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *BulkDeleteRecordsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *BulkDeleteRecordsResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
