// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetRecordVersionsRequest struct {
	// x-collaboration
	XCollaboration *string `header:"style=simple,explode=false,name=x-collaboration"`
	// Record id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Tenant Id
	DataPartitionID string `header:"style=simple,explode=false,name=data-partition-id"`
}

func (o *GetRecordVersionsRequest) GetXCollaboration() *string {
	if o == nil {
		return nil
	}
	return o.XCollaboration
}

func (o *GetRecordVersionsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetRecordVersionsRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

type GetRecordVersionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Record versions retrieved successfully.
	RecordVersions *components.RecordVersions
}

func (o *GetRecordVersionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRecordVersionsResponse) GetRecordVersions() *components.RecordVersions {
	if o == nil {
		return nil
	}
	return o.RecordVersions
}
