// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetSpecificRecordVersionRequest struct {
	// x-collaboration
	XCollaboration *string `header:"style=simple,explode=false,name=x-collaboration"`
	// Record id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Record version
	Version int64 `pathParam:"style=simple,explode=false,name=version"`
	// Filter attributes to restrict the returned fields of the record.  Usage: data.{record-data-field-name}.
	Attribute []string `queryParam:"style=form,explode=true,name=attribute"`
	// Tenant Id
	DataPartitionID string `header:"style=simple,explode=false,name=data-partition-id"`
}

func (o *GetSpecificRecordVersionRequest) GetXCollaboration() *string {
	if o == nil {
		return nil
	}
	return o.XCollaboration
}

func (o *GetSpecificRecordVersionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetSpecificRecordVersionRequest) GetVersion() int64 {
	if o == nil {
		return 0
	}
	return o.Version
}

func (o *GetSpecificRecordVersionRequest) GetAttribute() []string {
	if o == nil {
		return nil
	}
	return o.Attribute
}

func (o *GetSpecificRecordVersionRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

type GetSpecificRecordVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Record retrieved successfully.
	String *string
}

func (o *GetSpecificRecordVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSpecificRecordVersionResponse) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}
