// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type HealthMessageRequest struct {
	// Tenant Id
	DataPartitionID string `header:"style=simple,explode=false,name=data-partition-id"`
}

func (o *HealthMessageRequest) GetDataPartitionID() string {
	if o == nil {
		return ""
	}
	return o.DataPartitionID
}

type HealthMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Res *string
}

func (o *HealthMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *HealthMessageResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}
