// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type AppError struct {
	Code    *int    `json:"code,omitempty"`
	Reason  *string `json:"reason,omitempty"`
	Message *string `json:"message,omitempty"`
}

var _ error = &AppError{}

func (e *AppError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
