// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BulkUpdateRecordsResponse struct {
	RecordCount           *int     `json:"recordCount,omitempty"`
	RecordIds             []string `json:"recordIds,omitempty"`
	NotFoundRecordIds     []string `json:"notFoundRecordIds,omitempty"`
	UnAuthorizedRecordIds []string `json:"unAuthorizedRecordIds,omitempty"`
	LockedRecordIds       []string `json:"lockedRecordIds,omitempty"`
}

func (o *BulkUpdateRecordsResponse) GetRecordCount() *int {
	if o == nil {
		return nil
	}
	return o.RecordCount
}

func (o *BulkUpdateRecordsResponse) GetRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.RecordIds
}

func (o *BulkUpdateRecordsResponse) GetNotFoundRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.NotFoundRecordIds
}

func (o *BulkUpdateRecordsResponse) GetUnAuthorizedRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.UnAuthorizedRecordIds
}

func (o *BulkUpdateRecordsResponse) GetLockedRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.LockedRecordIds
}
