// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateUpdateRecordsResponse struct {
	RecordCount      *int     `json:"recordCount,omitempty"`
	RecordIds        []string `json:"recordIds,omitempty"`
	SkippedRecordIds []string `json:"skippedRecordIds,omitempty"`
	RecordIDVersions []string `json:"recordIdVersions,omitempty"`
}

func (o *CreateUpdateRecordsResponse) GetRecordCount() *int {
	if o == nil {
		return nil
	}
	return o.RecordCount
}

func (o *CreateUpdateRecordsResponse) GetRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.RecordIds
}

func (o *CreateUpdateRecordsResponse) GetSkippedRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.SkippedRecordIds
}

func (o *CreateUpdateRecordsResponse) GetRecordIDVersions() []string {
	if o == nil {
		return nil
	}
	return o.RecordIDVersions
}
