// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MultiRecordIds - Record ids
type MultiRecordIds struct {
	Records    []string `json:"records"`
	Attributes []string `json:"attributes,omitempty"`
}

func (o *MultiRecordIds) GetRecords() []string {
	if o == nil {
		return []string{}
	}
	return o.Records
}

func (o *MultiRecordIds) GetAttributes() []string {
	if o == nil {
		return nil
	}
	return o.Attributes
}
