// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MultiRecordInfo struct {
	Records        []Record `json:"records,omitempty"`
	InvalidRecords []string `json:"invalidRecords,omitempty"`
	RetryRecords   []string `json:"retryRecords,omitempty"`
}

func (o *MultiRecordInfo) GetRecords() []Record {
	if o == nil {
		return nil
	}
	return o.Records
}

func (o *MultiRecordInfo) GetInvalidRecords() []string {
	if o == nil {
		return nil
	}
	return o.InvalidRecords
}

func (o *MultiRecordInfo) GetRetryRecords() []string {
	if o == nil {
		return nil
	}
	return o.RetryRecords
}
