// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MultiRecordRequest - Record ids
type MultiRecordRequest struct {
	Records []string `json:"records"`
}

func (o *MultiRecordRequest) GetRecords() []string {
	if o == nil {
		return []string{}
	}
	return o.Records
}
