// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PatchOperation struct {
	Op    *string  `json:"op,omitempty"`
	Path  *string  `json:"path,omitempty"`
	Value []string `json:"value"`
}

func (o *PatchOperation) GetOp() *string {
	if o == nil {
		return nil
	}
	return o.Op
}

func (o *PatchOperation) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *PatchOperation) GetValue() []string {
	if o == nil {
		return []string{}
	}
	return o.Value
}
