// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PatchRecordsResponse struct {
	RecordCount       *int     `json:"recordCount,omitempty"`
	RecordIds         []string `json:"recordIds,omitempty"`
	NotFoundRecordIds []string `json:"notFoundRecordIds,omitempty"`
	FailedRecordIds   []string `json:"failedRecordIds,omitempty"`
	Errors            []string `json:"errors,omitempty"`
}

func (o *PatchRecordsResponse) GetRecordCount() *int {
	if o == nil {
		return nil
	}
	return o.RecordCount
}

func (o *PatchRecordsResponse) GetRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.RecordIds
}

func (o *PatchRecordsResponse) GetNotFoundRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.NotFoundRecordIds
}

func (o *PatchRecordsResponse) GetFailedRecordIds() []string {
	if o == nil {
		return nil
	}
	return o.FailedRecordIds
}

func (o *PatchRecordsResponse) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}
