// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RecordBulkUpdateParam - Records to be updated
type RecordBulkUpdateParam struct {
	Query RecordQuery      `json:"query"`
	Ops   []PatchOperation `json:"ops"`
}

func (o *RecordBulkUpdateParam) GetQuery() RecordQuery {
	if o == nil {
		return RecordQuery{}
	}
	return o.Query
}

func (o *RecordBulkUpdateParam) GetOps() []PatchOperation {
	if o == nil {
		return []PatchOperation{}
	}
	return o.Ops
}
