// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecordQuery struct {
	Ids []string `json:"ids"`
}

func (o *RecordQuery) GetIds() []string {
	if o == nil {
		return []string{}
	}
	return o.Ids
}
