// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecordVersions struct {
	RecordID *string `json:"recordId,omitempty"`
	Versions []int64 `json:"versions,omitempty"`
}

func (o *RecordVersions) GetRecordID() *string {
	if o == nil {
		return nil
	}
	return o.RecordID
}

func (o *RecordVersions) GetVersions() []int64 {
	if o == nil {
		return nil
	}
	return o.Versions
}
