// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Data struct {
}

type Meta struct {
}

type Record struct {
	ID       *string           `json:"id,omitempty"`
	Version  *int64            `json:"version,omitempty"`
	Kind     *string           `json:"kind,omitempty"`
	ACL      ACL               `json:"acl"`
	Legal    *Legal            `json:"legal,omitempty"`
	Data     map[string]Data   `json:"data"`
	Ancestry *RecordAncestry   `json:"ancestry,omitempty"`
	Meta     []map[string]Meta `json:"meta,omitempty"`
	Tags     map[string]string `json:"tags,omitempty"`
}

func (o *Record) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Record) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *Record) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

func (o *Record) GetACL() ACL {
	if o == nil {
		return ACL{}
	}
	return o.ACL
}

func (o *Record) GetLegal() *Legal {
	if o == nil {
		return nil
	}
	return o.Legal
}

func (o *Record) GetData() map[string]Data {
	if o == nil {
		return map[string]Data{}
	}
	return o.Data
}

func (o *Record) GetAncestry() *RecordAncestry {
	if o == nil {
		return nil
	}
	return o.Ancestry
}

func (o *Record) GetMeta() []map[string]Meta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *Record) GetTags() map[string]string {
	if o == nil {
		return nil
	}
	return o.Tags
}
