// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecordAncestry struct {
	Parents []string `json:"parents,omitempty"`
}

func (o *RecordAncestry) GetParents() []string {
	if o == nil {
		return nil
	}
	return o.Parents
}
